### ISSUE TITLE
Apple no longer accepting UIWebView

### ISSUE THREAD

**Issue by aborren** [klarna/kco-mobile-sdk#34]
The following message is being sent from Apple after uploading an app that has imported the KlarnaCheckoutSDK. 

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

It can easily be reproduced by creating an empty project that only imports your SDK. 

This is an urgent issue as Apple already has started rejecting apps using UIWebView API:s. You need to migrate and use WebKit and WKWebViews.

**Comment by gbanfalvikl** [comment]
Hi there!

Yeah, we're aware of the warning, however we have no way to avoid it completely:
1) The SDK supports merchants that integrate Klarna Checkout using `UIWebView` and co. so our code definitely has references to it. We can't remove support without breaking API commitments.
2) Some internal components (e.g. the In-App browser) are being migrated now to either `SFSafariViewController` or alternatives. This will be fixed in future releases.

The latest information we have is that apps built with the iOS 13 SDK will throw warnings but App Store Connect and/or Xcode won't stop developers. All we can do right now is to apologise for the nuisance. We'll remove the last references to `UIWebView` as soon as we can.

**Comment by sammcewan** [comment]
@gbanfalvikl Was initially confused by your first message so we need to clarify that, as per your final statement, you are removing references to UIWebView from this SDK? 

This is crucial for us to have some reassurance as we look to take on this as a dependency. We are in the final stages of completing a project to replace UIWebView entirely with WKWebView in our product.

Thanks in advance!

**Comment by omarbh** [comment]
Hi @sammcewan removing UIWebview is in our road map. I will closed this ticket as it's solved!
