### ISSUE TITLE
1.7.2 & 1.7.3 not available for android

### ISSUE THREAD

**Issue by casvanluijtelaar** [klarna/kco-mobile-sdk#72]
seems the latest versions aren't retrievable yet: https://x.klarnacdn.net/mobile-sdk/com/klarna/checkout/sdk/maven-metadata.xml

**Comment by NMGuner** [comment]
Hi @casvanluijtelaar, our SDK versioning is not matched between platforms hence the iOS SDK has 1.7.3 but the latest Android version is 1.7.1 as documented in the [changelog](https://github.com/klarna/kco-mobile-sdk/blob/master/CHANGELOG.md). This is mainly due to different fixes on different platforms, you are suggested and safe to use the latest version of the respective platform SDK.
